import { pageMetadata } from '@/src/data/site';
import { getFeaturedMenuItems, MENU_CATEGORIES, getMenuItemsByCategory } from '@/src/data/menu';
import { Action, FoodDrawing, Photo, SectionTitle, OrderFinish } from '@/src/components/after-dark/Shared';
import { LayerExplorer } from '@/src/components/after-dark/LayerExplorer';
import Link from 'next/link';
export const metadata = pageMetadata('Cheezish | Cheese, Taken Seriously.', 'Bold burgers, glorious melts. Explore the Cheezish restaurant concept after dark.', '/');
export default function HomePage() {
  const burgers = getFeaturedMenuItems();
  return <main className="ad-home">
    <section className="ad-hero ad-wrap">
      <div className="ad-hero-copy"><p className="ad-eyebrow"><span /> The burger house after dark</p><h1>CHEESE,<br />TAKEN<br /><em>SERIOUSLY.</em></h1><p className="ad-lead">A little messy. A lot of flavour.<br />Big burgers. Golden melts. Good company.</p><div className="ad-actions"><Action href="/menu">Find your burger</Action><Action href="/about" secondary>Our story</Action></div><p className="ad-hero-footnote">SMASH. MELT. REPEAT.<span>That’s the idea.</span></p></div>
      <div className="ad-hero-art"><Photo src="/images/menu/the-cheezish.jpg" alt="The Cheezish signature burger with golden melted cheddar and a toasted brioche bun" priority /><div className="ad-stamp">ALL ABOUT<br /><strong>THE MELT</strong><FoodDrawing /></div><div className="ad-hero-caption"><span>THE ORIGINAL CRAVING</span><strong>The Cheezish <span>£9.95</span></strong></div></div>
    </section>
    <div className="ad-ticker" aria-hidden="true"><span>BIG FLAVOUR</span><i>✳</i><span>GOLDEN MELTS</span><i>✳</i><span>NO BORING BURGERS</span><i>✳</i><span>CHEEZISH AFTER DARK</span></div>
    <section className="ad-section ad-wrap"><SectionTitle eyebrow="01 / House favourites" title="MEET YOUR NEXT CRAVING."><Link className="ad-text-link" href="/menu">Full menu ↗</Link></SectionTitle><div className="ad-signatures">{burgers.map((item,i)=><Link href="/menu#signature-burgers" className={i===0?'ad-signature ad-signature-feature':'ad-signature'} key={item.id}><Photo src={item.image!} alt={item.name} sizes={i===0?'(min-width: 900px) 640px, 100vw':'(min-width: 900px) 360px, 100vw'} /><div className="ad-signature-info"><p className="ad-eyebrow">{i===0?'The house signature':i===1?'Double the good stuff':'A little heat'}</p><h3>{item.name}<span>£{item.price.toFixed(2)}</span></h3><p>{item.description}</p></div></Link>)}</div></section>
    <section className="ad-ingredients"><div className="ad-wrap ad-split"><LayerExplorer /><div className="ad-editorial-copy"><p className="ad-eyebrow">02 / The good stuff inside</p><h2>EVERY LAYER.<br /><em>ANOTHER REASON.</em></h2><p className="ad-lead">The best bite is a balancing act. Rich, sharp, soft and crisp — all in one handful.</p><ol className="ad-ingredient-list"><li><span>01</span><div><h3>The golden start</h3><p>Soft brioche, toasted edges. The first and last bite.</p></div></li><li><span>02</span><div><h3>The main event</h3><p>A deeply browned patty meets a generous cheddar melt.</p></div></li><li><span>03</span><div><h3>The sharp finish</h3><p>Pickles and sauce bring the richness into balance.</p></div></li></ol></div></div></section>
    <section className="ad-section ad-wrap"><SectionTitle eyebrow="03 / Make it a meal" title="MORE THAN THE BURGER."><p>Something on the side.<br />Something to come back for.</p></SectionTitle><div className="ad-menu-preview">{MENU_CATEGORIES.slice(1).map((category,i)=><Link href={'/menu#'+category.id} key={category.id}><span className="ad-eyebrow">0{i+1}</span><h3>{category.label}<span aria-hidden="true">↗</span></h3><p>{getMenuItemsByCategory(category.id)[0].name}</p><strong>From £{Math.min(...getMenuItemsByCategory(category.id).map(x=>x.price)).toFixed(2)}</strong></Link>)}</div></section>
    <section className="ad-gallery-teaser ad-wrap"><div className="ad-gallery-teaser-copy"><p className="ad-eyebrow">04 / Eyes first. Appetite next.</p><h2>WORTH<br />A <em>CLOSE-UP.</em></h2><Action href="/gallery" secondary>Into the gallery</Action></div><Photo src="/images/menu/inferno.jpg" alt="Inferno burger, jalapeños and melted pepper jack" /><Photo src="/images/menu/double-melt.jpg" alt="Double Melt with caramelized onions" /></section>
    <section className="ad-story-teaser ad-wrap"><span className="ad-eyebrow">05 / Our point of view</span><h2>GOOD FOOD.<br />A LITTLE <em>ATTITUDE.</em></h2><Photo className="ad-story-detail" src="/images/burger-layers/01-top-bun.png" alt="The sesame brioche bun from the Cheezish ingredient artwork" sizes="240px" /><div><p>Cheezish is an idea with an appetite: a burger house where the food does the talking. Bold flavours, a warm welcome and absolutely no boring bites.</p><Link className="ad-text-link" href="/about">Get to know the concept ↗</Link></div></section>
    <OrderFinish />
  </main>;
}
